### ISSUE TITLE
Phone error rates below ~50%

### ISSUE THREAD

**Issue by bjtommychen** [dspavankumar/keras-kaldi#13]
Hi Kumar
      I got your code run with timit datasets.
      but I can't get same phone error rate like you. 
      your  is DNN (3 hidden layers of 1024 nodes, ReLU activations): 23.71%. but mine is only ~50%
      I used latest kaldi. use run_kt.sh.
      Would u post your log for reference. 
      Thanks.

      btw, I use tri2, and the script got 2000+ pdf from final.mdl.

**Comment by dspavankumar** [comment]
Hello, can you verify the points below?
1. What is the WER you get for tri2? If it is worse than 50%, then something went wrong in the GMM training or feature extraction.
2. Make sure tri2 directory (the one you provide as 'gmm' to train.py) was indeed used to generate the alignments you are using to train the DNNs. Have you changed the tree file or retrained in the same directory after generating alignments?

I don't have the log file anymore, I used a different machine to generate the results.

**Comment by bjtommychen** [comment]
Hi, Kumar
    Thanks for your clue !
    I think the problem is resolved now.
    Although the Keras evaluate() report acc ~50%, the RESULTS script print out WER ~25%.
    That means I got the almost same WER as yours.
    Thanks again for your project. It help me lot when dig in Kaldi.
